name: flutter_modifiers
description: A collection of useful extension function that make your flutter code a lot cleaner.
version: 0.0.2
homepage: https://github.com/drmas/flutter_modifiers

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
